kind: ConfigMap
apiVersion: v1
metadata:
  name: custom-config-toml
  namespace: gitlab-dev
data:
  config.toml: |-
     [[runners]]
       executor = "kubernetes"
       [runners.kubernetes]
         tls_verify = false
         pull_policy = ["if-not-present"]
         privileged = false
       [runners.kubernetes.pod_security_context]
         run_as_non_root = true
         run_as_user = 1000
       [[runners.kubernetes.volumes.empty_dir]]
         name = "containers-dir"
         mount_path = "/home/build/.local/share/containers"
       [[runners.kubernetes.volumes.empty_dir]]
         name = "runner-home-dir"
         mount_path = "/home/gitlab-runner"
       [[runners.kubernetes.volumes.empty_dir]]
         name = "helm-config"
         mount_path = "/.config"         
       [[runners.kubernetes.volumes.empty_dir]]
         name = "helm-cache"
         mount_path = "/.cache"         
       [[runners.kubernetes.volumes.empty_dir]]
         name = "oc-kube"
         mount_path = "/.kube"   